version: "3.9"

services:
  bogo-sort:
    depends_on:
      - redis
    image: iacopomelani/bogo-sort-cluster:latest
    ports:
      - 8888:8888
  redis:
    hostname: "redis"
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
volumes:
  redis_data: {}
